### ISSUE TITLE
[API getUserByUserName] thiếu dữ liệu trả về

### ISSUE THREAD

**Issue by NguyenAnhVuong** [ngocban284/Image-Lazer-Backend#14]
- getUserByUserName dữ liệu trả về phải có thêm
+ 1 mảng tên các ảnh đã tạo (createdImages).
+ 1 mảng object gồm tên các album đã lưu kèm theo một ảnh đầu tiên của album đó (albums).
+ followers
+ following

**Comment by ngocban284** [comment]
completed
