### ISSUE TITLE
[API getAlbumByUser] API hỏng :))

### ISSUE THREAD

**Issue by ghost** [ngocban284/Image-Lazer-Backend#22]
cần lắm nó trả về full thông tin Album của người dùng (Id người dùng có trong Token)
thông tin trả về là một mảng nhiều object Album ví dụ:
[
{
id: id của Album,
name: tên của Album,
description: miêu tả Album,
secret: true/false,
image: {
name: tên ảnh
src: /uploads/tên ảnh
height: chiều dọc ảnh
width: chiều ngang ảnh
},
{
id: 123,
name: Wibu,
description: zxcvxvsdfsdf,
secret: true,
image: {
name: nusinhZennomi.jpg
src: /uploads/nusinhZennomi.jpg
height: 900
width: 1600
},
]

**Comment by ngocban284** [comment]
completed
