### ISSUE TITLE
[API getUserByUserName] thiếu dữ liệu

### ISSUE THREAD

**Issue by NguyenAnhVuong** [ngocban284/Image-Lazer-Backend#24]
cần có thêm trường topic là mảng các topic mà người dùng đã chọn.
Ví dụ: topic: ['Anime', 'Thiên nhiên', 'Động vật', 'Du lịch'] ( tk mới thì topic: [])

**Comment by ngocban284** [comment]
completed

**Comment by NguyenAnhVuong** [comment]
thiếu followers và following Bản ơi

**Comment by ngocban284** [comment]
completed
