### ISSUE TITLE
[API getPostById] sai dữ liệu trả về, bảo mật kém

### ISSUE THREAD

**Issue by NguyenAnhVuong** [ngocban284/Image-Lazer-Backend#25]
dữ liệu hiện tại:
{
    "_id": "629b2d73faa251b925689a11",
    "user_id": {
        "_id": "629b2d60faa251b9256899fd",
        "userName": "@test2_3",
        "fullName": "Nguyen Anh vuongw",
        "age": 100,
        "email": "test2@gmail.com",
        "password": "$2b$10$zNRPikObXavKONaLGKECbeuyEibEdd1sYvItkFn.jM42A63PWhwIS",
        "avatar": "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
        "following_count": 0,
        "follower_count": 0,
        "topics": [],
        "createdAt": "2022-06-04T10:01:04.692Z",
        "updatedAt": "2022-06-10T03:21:45.419Z",
        "__v": 0,
        "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI5YjJkNjBmYWEyNTFiOTI1Njg5OWZkIiwiaWF0IjoxNjU0ODMxMzA1LCJleHAiOjE2NTUwOTA1MDV9.7X3-9fETbVR52DZD1fIbThyrj8L4BseO2C0X9bndj4Y",
        "refreshTokenExpiry": 1655090505,
        "followers": []
    },
    "album_id": "629b2d60faa251b9256899fe",
    "image": "b5e0d2ae-a0ac-4a6a-8dd7-2328db8398a7.jpg",
    "image_height": 2160,
    "image_width": 3840,
    "description": "sadfsadf",
    "link": "asdfasdf",
    "title": "sdfsadf",
    "topic": "Tranh",
    "createdAt": "2022-06-04T10:01:23.978Z",
    "updatedAt": "2022-06-04T10:01:23.978Z",
    "__v": 0,
    "likes": [],
    "comments": []
}

=> dữ liệu cần trả về:
{
    "_id": "629b2d73faa251b925689a11",
    "userInformation": {                               //đoạn này đổi tên trường
        "_id": "629b2d60faa251b9256899fd",
        "userName": "@test2_3",
        "fullName": "Nguyen Anh vuongw",
        "age": 100,
        "email": "test2@gmail.com",
        "password": "$2b$10$zNRPikObXavKONaLGKECbeuyEibEdd1sYvItkFn.jM42A63PWhwIS",                // bỏ trường này
        "avatar": "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
        "following_count": 0,
        "follower_count": 0,
        "topics": [],
        "createdAt": "2022-06-04T10:01:04.692Z",
        "updatedAt": "2022-06-10T03:21:45.419Z",
        "__v": 0, // ?
        "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI5YjJkNjBmYWEyNTFiOTI1Njg5OWZkIiwiaWF0IjoxNjU0ODMxMzA1LCJleHAiOjE2NTUwOTA1MDV9.7X3-9fETbVR52DZD1fIbThyrj8L4BseO2C0X9bndj4Y",                 // bỏ trường này
        "refreshTokenExpiry": 1655090505,               // bỏ trường này
        "followers": []
    },
    "album_id": "629b2d60faa251b9256899fe",
    "image": "b5e0d2ae-a0ac-4a6a-8dd7-2328db8398a7.jpg",
    "image_height": 2160,
    "image_width": 3840,
    "description": "sadfsadf",
    "link": "asdfasdf",
    "title": "sdfsadf",
    "topic": "Tranh",
    "createdAt": "2022-06-04T10:01:23.978Z",
    "updatedAt": "2022-06-04T10:01:23.978Z",
    "__v": 0, // ?
    "likes": [],
    "comments": []
}

**Comment by ngocban284** [comment]
completed

**Comment by NguyenAnhVuong** [comment]
userInformation:
age: 100
avatar: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg"
email: "test2@gmail.com"
followers: []
following_count: 0
fullName: "Nguyen Anh vuongw"
topics: []
userName: "@test2_3"
_id: "629b2d60faa251b9256899fd"
[[Prototype]]: Object
_id: "629b3377faa251b925689a4d"

cái followers và following_count rất là không đồng bộ nhé tại sao một cái là mảng còn 1 cái là số đáng ra cả 2 cùng là mảng chứ, 2 cái cùng kiểu dữ liệu mà mỗi cái trả về 1 kiểu

**Comment by ngocban284** [comment]
followers là danh sách người theo dõi
following_count là số người mình follow
follower_count là số người theo dõi mình

**Comment by NguyenAnhVuong** [comment]
followers là người theo dõi mình nó là mảng thì mình có thể biết đc ai follow mình đồng thời lấy length để tính ra số lượng
nhưng cái following có thể dùng cùng kiểu với followers để trả về nhiều thông  tin mà gọn gàng nhất thì m không dùng m lại đem t mỗi cái following_count thế đến lúc cần xem mình theo dõi ai thì sao xem đc

**Comment by ngocban284** [comment]
completed
