### ISSUE TITLE
[Album API] Thiếu api lấy thông tin album bằng id

### ISSUE THREAD

**Issue by NguyenAnhVuong** [ngocban284/Image-Lazer-Backend#28]
bên front sẽ gửi id một album đến back
Ví dụ về dữ liệu trả về 
{
errorCode: 0,
message: "Lấy thông tin album thành công!",
name: "Tên album"
userName: @test2_3 // userName chủ album
fullName: "Nguyễn Anh Vương" //tên người chủ album,
secret: true,
description: "asdfasdfasdfasdf",
images: [                                 //Mảng chứa tất cả ảnh trong album đó
{
            id: "629b2d73faa251b925689a11",
            name: "b5e0d2ae-a0ac-4a6a-8dd7-2328db8398a7.jpg",
            src: "/uploads/b5e0d2ae-a0ac-4a6a-8dd7-2328db8398a7.jpg",
            height: 2160,
            width: 3840
        },
{
            id: "629b2d73faa251b925689a11",
            name: "b5e0d2ae-a0ac-4a6a-8dd7-2328db8398a7.jpg",
            src: "/uploads/b5e0d2ae-a0ac-4a6a-8dd7-2328db8398a7.jpg",
            height: 2160,
            width: 3840
        },
]
}

**Comment by ngocban284** [comment]
completed
