### ISSUE TITLE
[API Search] API search user

### ISSUE THREAD

**Issue by NguyenAnhVuong** [ngocban284/Image-Lazer-Backend#35]
Front sẽ gửi một chuỗi search qua param, chuỗi search đó có thể là fullName hoặc userName bên Back sẽ dùng chuỗi đó để lấy tất cả user mà có fullName (chuyển về chữ thường) chứa search (chuyển về chữ thường) hoặc có userName(chuyển về chữ thường) chứa search (chuyển về chữ thường).
Dữ liệu trả về là thông tin user. Ví dụ: chuỗi search là 'vuo' hoặc 'Vươ', ...
{
errorCode: 0,
users: [
{
avatarSrc: '/uploads/default_avatar.png'     // link src avatar
fullName: Nguyễn Anh Vương
userName: @navuong2001
},
{
avatarSrc: '/uploads/default_avatar.png'     // link src avatar
fullName: Nguyễn Anh Vương 2
userName: @navuong2001
}
]

**Comment by ngocban284** [comment]
Completed
